---
- name: Check if Go is already installed.
  command: /usr/local/go/bin/go version
  ignore_errors: true
  register: go_version_result
  changed_when: false

- name: Download Go.
  get_url:
    url: "{{ go_download_url }}"
    dest: /tmp/{{ go_tarball }}
  when: go_version_result is failed

- name: Extract Go.
  unarchive:
    src: /tmp/{{ go_tarball }}
    dest: /usr/local
    copy: false
  when: go_version_result is failed

- name: Add Go to to system-wide $PATH.
  ansible.builtin.lineinfile:
    path: /etc/paths.d/go
    line: /usr/local/go/bin
    create: true
