---
- name: Check if Go is already installed.
  command: go version
  ignore_errors: true
  register: go_version_result
  changed_when: false

- name: Check if gvm is already installed.
  command: ~/bin/gvm version
  ignore_errors: true
  register: gvm_version_result
  changed_when: false

- name: Download gvm.
  get_url:
    url: "{{ gvm_download_url }}"
    dest: ~/bin/gvm
    mode: '0755'
  when:
    - go_version_result is failed
    - gvm_version_result is failed

- name: Install Go.
  shell: eval $(gvm {{ go_version }})
  when:
    - go_version_result is failed
    - gvm_version_result is failed
