---
- name: Check if Go is already installed.
  command: /usr/local/go/bin/go version
  ignore_errors: true
  register: go_version_result
  changed_when: false

- name: Download Go.
  get_url:
    url: "{{ go_download_url }}"
    dest: /usr/local/src/{{ go_tarball }}
  when: go_version_result is failed

- name: Extract Go.
  unarchive:
    src: /usr/local/src/{{ go_tarball }}
    dest: /usr/local
    copy: false
  when: go_version_result is failed

- name: Add Go to to system-wide $PATH.
  copy:
    dest: /etc/profile.d/go-path.sh
    content: |-
      export PATH=$PATH:/usr/local/go/bin
  when: go_version_result is failed
