---
- name: Load a variable file based on the OS type, or a default if not found.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - default.yml
      paths:
        - 'vars'

- name: Install Go for Linux
  import_tasks: linux.yml
  when: ansible_facts['os_family']|lower in ['redhat', 'debian', 'suse']

- name: Install Go for Darwin
  import_tasks: darwin.yml
  when: ansible_facts['os_family']|lower == 'darwin'

- name: Install Go for Windows
  import_tasks: windows.yml
  when: ansible_facts['os_family']|lower == 'windows'
