---
- name: Check if Go is already installed.
  ansible.windows.win_shell: go version
  ignore_errors: true
  register: go_version_result
  changed_when: false

- name: Install Go.
  win_package:
    path: "{{ go_download_url }}"
    state: present
    arguments:
      - /qn
  when: go_version_result is failed

- name: Ensure that Go is present on the global system path
  ansible.windows.win_path:
    elements:
    - '{{ go_install_path }}\Go\bin'
  when: go_version_result is failed
