---
- name: Check if Go is already installed.
  command: go version
  ignore_errors: true
  register: go_version_result
  changed_when: false

- name: Install Go.
  win_package:
    path: "{{ go_download_url }}"
    state: present
    arguments:
      - /qn
  when: go_version_result is failed
