---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
    - name: Install tar with Yum.
      yum:
        name: tar
        state: present
      when: ansible_distribution == Amazon
      changed_when: false

  roles:
    - role: mdelapenya.go

  tasks:
    - name: Verify that Go is installed and available in the $PATH.
      command: go version
      environment:
        PATH: /usr/local/go/bin:{{ ansible_env.PATH }}
      changed_when: false
