---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: instance
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-../resources/converge.yml}
